namespace OKQ8.ServiceLayer
{
    public enum CardType
    {
        /* TODO: Danish types
        CARDTYPE_ALL,
        CARDTYPE_PRIVATE,
        CARDTYPE_CORBORATE,
        CARDTYPE_DIESEL,
        CARDTYPE_CORBORATEPLUS,
        CARDTYPE_TRANSPORT,
        LIC_CARD,
        CARDTYPE_F24_PRIVATE,
        CARDTYPE_F24_PLUS,
        IDS_CARD,
        IDS_KEY_CARD,
        IDS_CARD_LOGO,
        IDS_DALLAS_CARD,
        IDS_COMBI_CARD,
        IDS_COMBI_KEY_CARD,
        IDS_COMBI_KEY_CARD_LOGO,
        IDS_COMBI_DALLAS_CARD,
        IDS_HOMETANKCARD,
        IDS_HOMETANK_KEYCARD,
        IDS_HOMETANKCARDLOGO,
        IDS_HOMETANKDALLQSKEYCARD,
        IDS_SERVICECARD,
        IDS_SERVICEKEYCARD,
        IDS_SERVICEDALLASCARD,
        IDS_WANCARD,
        IDS_WANKEYCARD,
        IDS_WANKEYEXTRA,
        UNKNOWN,
        */
    }
}